server:
  port: 9090

spring:
  config:
    import: env.properties

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/read_log_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

google:
  ai:
    api-key: ${GEMINI_API_KEY}

client:
  aladin:
    ttbKey: ${ALADIN_KEY}

apiKey: ${API_KEY}

secretKey: ${SECRET_KEY}