spring:
  config:
    import: env.properties

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://book-read-management.cja8esuaszdy.ap-northeast-2.rds.amazonaws.com/book_read_management
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

apiKey: abcd1234