spring:
  config:
    import: env.properties

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/read_log_db
    username: ${DB_USERNAME}
    password:

apiKey: abcd1234