server:
  port: 9090

spring:
  config:
    import: env.properties

  datasource:
    url: jdbc:mysql://localhost:3306/read_log_db

  data:
    redis:
      host: 117.52.84.99
      port: 16379

myDomain: "http://localhost:9090"

file:
  upload-dir: /Users/hwjeong/IdeaProjects/book_read_management/src/main/resources/upload

logging:
  level:
    com.liber.book_read_management.client.AladinClient: DEBUG