package com.liber.book_read_management.repository

import com.liber.book_read_management.entities.RecommendationHistorySourceLog
import org.springframework.data.jpa.repository.JpaRepository

interface RecommendationHistorySourceLogRepository : JpaRepository<RecommendationHistorySourceLog, Long>
