name: Build and Push to ECR

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 체크아웃
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2   # 서울 리전

      # 3. ECR 로그인
      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Docker 이미지 빌드 & 태깅
      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t book-read-management-api:$IMAGE_TAG --platform linux/amd64 .
          docker tag book-read-management-api:$IMAGE_TAG ${{ steps.ecr.outputs.registry }}/book-read-management-api:$IMAGE_TAG

      # 5. ECR 푸시
      - name: Push to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker push ${{ steps.ecr.outputs.registry }}/book-read-management-api:$IMAGE_TAG
          
      - name: Get image digest
        id: img
        run: |
          DIGEST=$(aws ecr describe-images \
            --repository-name book-read-management-api \
            --image-ids imageTag=${{ github.sha }} \
            --query 'imageDetails[0].imageDigest' --output text)
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Render taskdef
        run: |
          sed "s|<ECR_URI>@<DIGEST>|${{ steps.ecr.outputs.registry }}/book-read-management-api@${{ steps.img.outputs.digest }}|g" taskdef.json > taskdef.rendered.json

      - name: Register new task definition
        id: reg
        run: |
          REVISION=$(aws ecs register-task-definition \
            --cli-input-json file://taskdef.rendered.json \
            --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "td_arn=$REVISION" >> $GITHUB_OUTPUT

      - name: Scale down to 0
        run: |
          aws ecs update-service \
            --cluster book_read_management \
            --service book_read_management-service-oruq1qnd \
            --deployment-configuration "maximumPercent=100,minimumHealthyPercent=0"

      - name: Scale down to 0
        run: |
          aws ecs update-service \
            --cluster book_read_management \
            --service book_read_management-service-oruq1qnd \
            --desired-count 0

      - name: Wait until service stable
        run: |
          aws ecs wait services-stable \
            --cluster book_read_management \
            --services book_read_management-service-oruq1qnd

      - name: Scale up to 1
        run: |
          aws ecs update-service \
            --cluster book_read_management \
            --service book_read_management-service-oruq1qnd \
            --desired-count 1 \
            --task-definition ${{ steps.reg.outputs.td_arn }}

      - name: Wait until service stable
        run: |
          aws ecs wait services-stable \
            --cluster book_read_management \
            --services book_read_management-service-oruq1qnd
            --cli-read-timeout 300